# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Xiang (Sean) Li
email: xngli@umich.edu
description: > # this means to ignore newlines until "baseurl:"
  Personal website of Xiang (Sean) Li, PhD student at University of Michigan
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000/" # the base hostname & protocol for your site
twitter_username: xiang_li_
github_username:  xngli

# Build settings
markdown: kramdown

# collections
collections:
- my_collection
collections:
  research:
    output: true
